// data.js
export const fakeData = {
    products: [
      { id: 1, name: 'Keychain A', price: 5, category: 'Keychains', stock: 50 },
      { id: 2, name: 'Mug B', price: 10, category: 'Mugs', stock: 30 },
      { id: 3, name: 'Keychain C', price: 7, category: 'Keychains', stock: 20 },
      { id: 4, name: 'Mug D', price: 12, category: 'Mugs', stock: 15 },
      { id: 5, name: 'Keychain E', price: 6, category: 'Keychains', stock: 60 },
      { id: 6, name: 'Mug F', price: 8, category: 'Mugs', stock: 45 },
      { id: 7, name: 'Keychain G', price: 5, category: 'Keychains', stock: 10 },
      { id: 8, name: 'Mug H', price: 9, category: 'Mugs', stock: 35 },
      { id: 9, name: 'Keychain I', price: 6, category: 'Keychains', stock: 25 },
      { id: 10, name: 'Mug J', price: 11, category: 'Mugs', stock: 40 },
      { id: 11, name: 'Keychain K', price: 5, category: 'Keychains', stock: 50 },
      { id: 12, name: 'Mug L', price: 10, category: 'Mugs', stock: 30 },
      { id: 13, name: 'Keychain M', price: 7, category: 'Keychains', stock: 20 },
      { id: 14, name: 'Mug N', price: 12, category: 'Mugs', stock: 15 },
      { id: 15, name: 'Keychain O', price: 6, category: 'Keychains', stock: 60 },
      { id: 16, name: 'Mug P', price: 8, category: 'Mugs', stock: 45 },
      { id: 17, name: 'Keychain Q', price: 5, category: 'Keychains', stock: 10 },
      { id: 18, name: 'Mug R', price: 9, category: 'Mugs', stock: 35 },
      { id: 19, name: 'Keychain S', price: 6, category: 'Keychains', stock: 25 },
      { id: 20, name: 'Mug T', price: 11, category: 'Mugs', stock: 40 },
    ],
    categories: [
      { id: 1, name: 'Keychains' },
      { id: 2, name: 'Mugs' },
      { id: 3, name: 'T-shirts' },
      { id: 4, name: 'Hats' },
      { id: 5, name: 'Postcards' },
    ],
    orders: [
      { id: 1, customer: 'John Doe', total: 25, status: 'Pending', date: '2024-12-08' },
      { id: 2, customer: 'Jane Smith', total: 45, status: 'Shipped', date: '2024-12-07' },
      { id: 3, customer: 'Mark Johnson', total: 15, status: 'Delivered', date: '2024-12-06' },
      { id: 4, customer: 'Emily White', total: 50, status: 'Pending', date: '2024-12-05' },
      { id: 5, customer: 'Sarah Brown', total: 20, status: 'Shipped', date: '2024-12-04' },
      { id: 6, customer: 'Michael Green', total: 30, status: 'Delivered', date: '2024-12-03' },
      { id: 7, customer: 'David Lee', total: 35, status: 'Pending', date: '2024-12-02' },
      { id: 8, customer: 'Chris Kim', total: 40, status: 'Shipped', date: '2024-12-01' },
      { id: 9, customer: 'Jessica Adams', total: 50, status: 'Delivered', date: '2024-11-30' },
      { id: 10, customer: 'Brian Harris', total: 60, status: 'Pending', date: '2024-11-29' },
      { id: 11, customer: 'Olivia Clark', total: 25, status: 'Shipped', date: '2024-11-28' },
      { id: 12, customer: 'Matthew Scott', total: 55, status: 'Delivered', date: '2024-11-27' },
      { id: 13, customer: 'Laura Lewis', total: 30, status: 'Pending', date: '2024-11-26' },
      { id: 14, customer: 'Daniel Walker', total: 40, status: 'Shipped', date: '2024-11-25' },
      { id: 15, customer: 'Sophia Allen', total: 45, status: 'Delivered', date: '2024-11-24' },
      { id: 16, customer: 'James Young', total: 35, status: 'Pending', date: '2024-11-23' },
      { id: 17, customer: 'Grace King', total: 50, status: 'Shipped', date: '2024-11-22' },
      { id: 18, customer: 'Liam Turner', total: 60, status: 'Delivered', date: '2024-11-21' },
      { id: 19, customer: 'Ella Perez', total: 20, status: 'Pending', date: '2024-11-20' },
      { id: 20, customer: 'Lucas Evans', total: 30, status: 'Shipped', date: '2024-11-19' },
    ],
  };
  